server.port=8003
spring.application.name=servicio-prestamos

# URLs de los servicios dependientes
# En Docker Compose se sobreescriben con nombres de contenedor
# En desarrollo local apuntan a localhost
libros.service.url=http://localhost:8001
usuarios.service.url=http://localhost:8002

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

management.endpoints.web.exposure.include=health,info

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest